### ISSUE TITLE
为什么只能用python3.5

### ISSUE THREAD

**Issue by 2401ch** [tensorflower/face-recognition#1]
你好，为什么python3.6 和python3.7用不了 ？

**Comment by tensorflower** [comment]
你好，并不是只能使用3.5，而是因为工作繁忙，暂时提供了linux 大家基本都会有的 python3.5版本，后续有空会发布更多支持的版本

**Comment by liquor233** [comment]
如果我要用3.6，我要怎么重新编译阿
